### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by chewi** [tagomoris/fluent-plugin-route#11]
The Apache-2.0 license mentioned in the README.md file doesn't match the MIT license found in the LICENSE file. The `APLv2` license string used in the gemspec is also not a standard label. Please use one from [SPDX](https://spdx.org/licenses/), probably either `Apache-2.0` or `MIT`.

**Comment by tagomoris** [comment]
Thank you for pointing it. #12 fixes this.
